VERILOG = ../src/ulx4m_top.v ../src/uart/acia.v ../src/keyboard/ps2.v ../src/keyboard/hid.v \
          ../src/memory/dpram.v ../src/memory/dpram2.v ../src/memory/dprom.v ../src/memory/rom.v \
          ../src/memory/ram.v ../src/memory/sdram.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
          ../src/lattice/ecp5pll.sv \
          ../src/spi_display/lcd_video.v \
          ../src/spi_display/hex_decoder_v.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v ../src/osd/spi_ram_btn.v \
	  ../src/osd/spirw_slave_v.v \
	  ../src/video/video.v ../src/video/hdmi.v \
          ../src/jt49/jt49.v ../src/jt49/jt49_bus.v  ../src/jt49/jt49_exp.v ../src/jt49/jt49_eg.v \
          ../src/jt49/jt49_div.v ../src/jt49/jt49_noise.v ../src/jt49/jt49_cen.v \
	  ../src/u765/u765.sv

PIN_DEF = ulx4m_v002.lpf

include ulx4m.mk

