VERILOG = ../src/top.v ../src/uart/acia.v ../src/keyboard/ps2.v ../src/keyboard/hid.v \
          ../src/memory/dpram.v ../src/memory/dprom.v ../src/memory/rom.v \
          ../src/memory/ram.v ../src/memory/sdram.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
          ../src/lattice/ecp5pll.sv \
          ../src/spi_display/lcd_video.v \
          ../src/spi_display/hex_decoder_v.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v ../src/osd/spi_ram_btn.v \
	  ../src/osd/spirw_slave_v.v \
	  ../src/video/video.v ../src/video/hdmi.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

